version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/admin-side/
hooks:
  ApplicationStop:
    - location: ./stop.sh
      timeout: 120 
      runas: root
  ApplicationStart:
    - location: ./start.sh
      timeout: 120
      runas: ec2-user
