version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...  
      - pip install awscli --upgrade --user
  build:
    commands:
      - echo Build started on `date`          
      - npm install
      - ls -l
artifacts:
  files:
    - '**/*'
 
