version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      #nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...  
      - pip install awscli --upgrade --user
      - chmod +x install-node.sh
      - ./install-node.sh
  build:
    commands:
      - echo Build started on `date`          
      - npm cache clean --force && npm install && npm run build      
      - ls -l
artifacts:
  files:
    - '**/*'
 
