version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      #nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...  
      - pip install awscli --upgrade --user
      - chmod +x install-node.sh
      - ./install-node.sh
  build:
    commands:
      - echo Build started on `date`   
      - rm package-lock.json
      - npm cache clean --force && npm install && yarn build
      - aws s3 sync . s3://congenco-artifacts/admin-backend
      - ls -l
artifacts:
  files:
    - '**/*'
 
